# =============================================
# PROJECT METADATA
# =============================================

title:          "Assemble &raquo; Pattern Lab"

# =============================================
# DEST CONFIG
# =============================================

base:           _gh_pages
dest:           <%= site.base %>
assets:         <%= site.base %>/public

# =============================================
# SOURCE CONFIG
# =============================================

# Data
data:           data

# Templates
structure:      templates
includes:       <%= site.structure %>/includes
layouts:        <%= site.structure %>/layouts
layout:         default
layoutext:      .hbs

# Extensions
helpers:
- <%= site.structure %>/_helpers

plugins:
- assemble-contrib-permalinks


# =============================================
# PATTERN LAB TEMPLATES
# =============================================

patterns:       patterns
atoms:          <%= site.patterns %>/00-atoms
molecules:      <%= site.patterns %>/01-molecules
organisms:      <%= site.patterns %>/02-organisms
templates:      <%= site.patterns %>/03-templates
pages:          <%= site.patterns %>/04-pages
